name: 'weather_air_quality'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["../data"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  weather_air_quality:
    +materialized: view